import React, { FC, ReactNode, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { AiOutlineClose, AiOutlineMenu } from 'react-icons/ai';
import { useRouter } from 'next/router';

import styles from './Navbar.module.css';
import { bgColor, bgImage, navbarColor } from '../utils';

interface Props {
	children: ReactNode;
	title: string;
}

const Navbar: FC<Props> = ({ children, title }) => {
	const [nav, setNav] = useState(false);
	const { pathname } = useRouter();

	const toggleNavbar = () => {
		setNav((prev) => !prev);
	};

	return (
		<>
			<Head>
				<title>{`Ricardo | ${title}`}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
				<link rel="manifest" href="/site.webmanifest" />
				<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
				<meta name="msapplication-TileColor" content="#da532c" />
				<meta name="theme-color" content="#ffffff" />
			</Head>
			<div className={bgImage(pathname)}>
				<div className={`flex items-center justify-center w-[100%] ${bgColor(pathname)}`}>
					<div className="flex justify-between items-center w-[100%] max-w-[1240px] px-4 2xl:px-16 pt-6 ">
						<Link href="/" className={styles.logo}>
							<Image
								src="https://res.cloudinary.com/dlz1bhh8j/image/upload/v1672333574/skills/zudmjm7cmmpkklfqtvs0.png"
								alt="portfolio_logo"
								width={100}
								height={25}
							/>
						</Link>
						<div>
							<ul className="hidden md:flex">
								<Link
									className={pathname === '/' ? styles.navbarActiveLink : styles.navbarLink}
									href="/"
								>
									Home
								</Link>
								<Link
									className={pathname === '/about' ? styles.navbarActiveLink : styles.navbarLink}
									href="/about"
								>
									About
								</Link>
								<Link
									className={pathname === '/skills' ? styles.navbarActiveLink : styles.navbarLink}
									href="/skills"
								>
									Skills
								</Link>
								<Link
									className={pathname === '/projects' ? styles.navbarActiveLink : styles.navbarLink}
									href="/projects"
								>
									Projects
								</Link>
								<Link
									className={pathname === '/contact' ? styles.navbarActiveLink : styles.navbarLink}
									href="/contact"
								>
									Contact
								</Link>
							</ul>
							<div onClick={toggleNavbar} className="md:hidden font-bold">
								<AiOutlineMenu size={30} />
							</div>
						</div>
					</div>
				</div>

				<div className={nav ? 'md:hidden fixed left-0 top-0 w-full h-[100%] bg-[#000]/50' : ''}>
					<div
						className={
							nav
								? `fixed left-0 top-0 w-[55%] min-[500px]:w-[45%] min-[600px]:w-[40%] h-[100%] ${navbarColor(
										pathname,
								  )} py-10 px-6 ease-in duration-500`
								: 'fixed left-[-100%] top-0 p-10 ease-in duration-500 bg-[#000]/50'
						}
					>
						<div>
							<div className="flex w-full items-center justify-between ">
								<Image
									src="https://res.cloudinary.com/dlz1bhh8j/image/upload/v1672333574/skills/zudmjm7cmmpkklfqtvs0.png"
									alt="logo"
									width={77}
									height={35}
								/>
								<div
									onClick={toggleNavbar}
									className="cursor-pointer rounded-full p-1 bg-[#ffffff]"
								>
									<AiOutlineClose size={18} className="text-[#24305e]" />
								</div>
							</div>
							<div className="border-b border-[#ffffff]-300 mt-7" />
						</div>
						<div className="py-4">
							<ul className="uppercase flex flex-col">
								<Link className="py-4 text-lg" href="/" onClick={() => setNav(!nav)}>
									Home
								</Link>
								<Link className="py-4 text-lg" href="/about" onClick={() => setNav(!nav)}>
									About
								</Link>
								<Link className="py-4 text-lg" href="/skills" onClick={() => setNav(!nav)}>
									Skills
								</Link>
								<Link className="py-4 text-lg" href="/projects" onClick={() => setNav(!nav)}>
									Projects
								</Link>
								<Link className="py-4 text-lg" href="/contact" onClick={() => setNav(!nav)}>
									Contact
								</Link>
							</ul>
						</div>
					</div>
				</div>
				<div className={`w-[100%] flex grow items-center justify-center ${bgColor(pathname)}`}>
					{children}
				</div>
			</div>
		</>
	);
};

export default Navbar;
