import Head from 'next/head';
import { FaGithub, FaLinkedinIn } from 'react-icons/fa';
import { AiOutlineMail } from 'react-icons/ai';
import { BsFillPersonLinesFill } from 'react-icons/bs';

import { Navbar } from '../components';

const Home = () => {
	return (
		<>
			<Head>
				<title>Richard | Front-End Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar>
				<div className="text-center">
					<h1 className="py-4 text-700">
						Hi, I&apos;m <span className="text-[#24305e]">Ricardo</span>
					</h1>
					<h1 className="py-4 text-700">A Full Stack Web Developer</h1>
					<p className="py-4 text-600 text-base min-[420px]:text-2xl max-w-[70%] m-auto">
						I&apos;m a developer capable to work on front-end web applications, back-end technology
						and mobile applications.
					</p>
					<div className="flex items-center justify-between max-w-[330px] m-auto py-4">
						<div className="bg-[#ffffff]/70 rounded-full shadow-lg shadow-400 p-6 cursor-pointer hover:scale-110 hover:bg-[#ffffff] ease-in duration-300">
							<FaLinkedinIn className="text-[#24305e]" />
						</div>
						<div className="bg-[#ffffff]/70 rounded-full shadow-lg shadow-400 p-6 cursor-pointer hover:scale-110 hover:bg-[#ffffff] ease-in duration-300">
							<FaGithub className="text-[#24305e]" />
						</div>
						<div className="bg-[#ffffff]/70 rounded-full shadow-lg shadow-400 p-6 cursor-pointer hover:scale-110 hover:bg-[#ffffff] ease-in duration-300">
							<AiOutlineMail className="text-[#24305e]" />
						</div>
						<div className="bg-[#ffffff]/70 rounded-full shadow-lg shadow-400 p-6 cursor-pointer hover:scale-110 hover:bg-[#ffffff] ease-in duration-300">
							<BsFillPersonLinesFill className="text-[#24305e]" />
						</div>
					</div>
				</div>
			</Navbar>
		</>
	);
};

export default Home;
